{
    'name': 'Tender Management',
    'version': '18.0.1.0.0',
    'summary': 'Comprehensive tender and bidding management system for Odoo 18',
    'category': 'Procurement',
    'author': 'Your Company',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'purchase',
        'sale',
        'account',
        'web',
    ],
    'data': [
        'data/ir_sequence_data.xml',
        'data/tender_data.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/tender_announcement_views.xml',
        'views/tender_bid_views.xml',
        'views/tender_vendor_views.xml',
        'views/tender_evaluation_views.xml',
        'views/tender_approval_views.xml',
        'views/menu_views.xml',
        'reports/tender_reports.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': ['static/description/icon.png'],
}
